[profile.default]
src = "contracts/src"
test = "contracts/test"
out = "contracts/out"
script = "contracts/script"
cache_path = "contracts/cache"
broadcast = "contracts/broadcast"
libs = ["dependencies"]
auto_detect_remappings = true
solc = "0.8.20"
evm_version = "shanghai"
optimizer_runs = 200
allow_internal_expect_revert = true

[soldeer]
recursive_deps = true
remappings_location = "txt"
remappings_version = false

[dependencies]
tnt-core = { version = "0.5.0", git = "https://github.com/tangle-network/tnt-core.git" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
